query IdentityBySponsorId($condition: IdentityCondition!) {
  allIdentities(condition: $condition) {
    nodes {
      id
      tenantId
      name
      displayName
      mrn
      slug
      email
    }
  }
}
