query IdentityById($condition: IdentityCondition!) {
  allIdentities(condition: $condition) {
    nodes {
      id
      memberId
      tenantId
      name
      displayName
      mrn
      slug
      email
      profileUrl
    }
  }
}
