query Member($input: MemberSearchCondition!) {
  members(condition: $input) {
    nodes {
      firstName
      lastName
      id
      birthdate
      tenantId
      name
      displayName
      mrn
      slug
      contacts {
        id
        emails {
          id
          email
        }
      }
      profileUrl
    }
  }
}
