query Member($input: MemberSearchCondition!) {
  members(condition: $input) {
    nodes {
      id
      birthdate
      tenantId
      name
      displayName
      mrn
      slug
      contactEmail
      profileUrl
    }
  }
}
