query auth($creds: Credentials!) {
  authenticate(input: $creds) {
    token
    success
    principal {
      role
      username
      displayName
      identityId
      memberId
      permissions
    }
  }
}
