mutation auth($creds: Credentials!) {
  login(input: $creds) {
    token
    success
    reason
    issued
    principal {
      username
      identityId
      memberId
      member {
        displayName
        contacts {
          id
        }
      }
    }
  }
}
