query principal {
  getPrincipal {
    role
    displayName
    username
    identityId
    tenantId
    memberId
    permissions
    member {
      firstName
      lastName
      id
      birthdate
      tenantId
      name
      displayName
      mrn
      slug
      slugs(priority: 0) {
        slug
      }
      sponsor {
        displayName
      }
      joinedOn
      tags
      contacts {
        id
        emails {
          id
          email
        }
      }
      profileUrl
      tenantIntegrations {
        id
        tenantIntegrationId
        integrationOid
        integrationStatusId
        metadata
        priority
        name
        key
      }
      customer {
        subscriptions {
          metadata
          status
        }
      }
    }
    tenant {
      id
      baseUrl
      name
      slug
      integrations {
        id
        priority
        metadata
        statusId
        name
        key
      }
    }
  }
}
