query principal {
  principal {
    role
    displayName
    username
    identityId
    tenantId
    memberId
    permissions {
      id
      key
      name
    }
    member {
      id
      name
      displayName
      contacts {
        id
      }
    }
  }
}
