query principal {
  getPrincipal {
    role
    displayName
    username
    identityId
    tenantId
    memberId
    permissions
    member {
      id
      name
      displayName
      contacts {
        id
      }
    }
  }
}
