query SalesBySeller($saleCondition:SaleCondition!){
  allSales(condition:$saleCondition){
    nodes{
      totalAmount,
      totalPoints,
      commissionableAmount,
      commissionablePoints,
      day,
      month,
      year
    }
  }
}