query teamStatSummaryByDepth($rangeInput: RangedSaleSummaryInput!) {
  teamStatSummaryByDepth(input: $rangeInput) {
    commissionableAmount
    commissionablePoints
    totalAmount
    totalPoints
    displayName
    salesCount
  }
}
