query teamStatsByLevel($teamInput: TeamStatsInput) {
  teamStatsByLevel(input: $teamInput) {
    memberId
    tenantId
    personal
    firstLevel
    secondLevel
    thirdLevel
    fourthLevel
  }
}
